# Generated by Django 3.2.19 on 2023-06-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreproduct', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=300)),
                ('precio', models.IntegerField(verbose_name=10)),
                ('stock', models.IntegerField(verbose_name=10)),
                ('foto', models.ImageField(upload_to='Inicioproject')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=45)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('contraseña', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField()),
                ('total', models.IntegerField(verbose_name=10)),
                ('estado', models.CharField(max_length=20)),
                ('carrito', models.IntegerField(verbose_name=10)),
            ],
        ),
    ]
