# Generated by Django 3.2.19 on 2023-06-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapatilla',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
