# Generated by Django 3.2.19 on 2023-06-07 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='codigoMarca',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Código de la zapatilla'),
        ),
        migrations.AlterField(
            model_name='zapatilla',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
