# Generated by Django 3.2.19 on 2023-06-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_zapatilla_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='codigoMarca',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Código de la zapatilla'),
        ),
    ]
